# Generated by Django 4.2 on 2023-06-09 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flowers',
            name='description',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='other',
            name='description',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
    ]
