# Generated by Django 4.2 on 2023-06-09 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowers', '0002_alter_flowers_description_alter_other_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flowers',
            name='description',
            field=models.TextField(default='flower', verbose_name='Описание'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='other',
            name='description',
            field=models.TextField(default=1, verbose_name='Описание'),
            preserve_default=False,
        ),
    ]
